




.build/mega2560/src/orc/orc.cpp : src/orc/orc.ino
	@mkdir -p .build/mega2560/src/orc
	@echo [93msrc/orc/orc.ino[0m
	@/usr/local/Cellar/ino/0.3.6/libexec/bin/ino preproc  -o $@ $^


all : .build/mega2560/src/orc/orc.cpp
	@true

